FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Taipei /etc/localtime
RUN apt-get update&&apt-get install -y clamav clamav-daemon \
    &&dpkg-reconfigure --frontend noninteractive tzdata 

RUN freshclam

EXPOSE 3010

CMD clamscan --exclude-dir=".git" -r /scan
